### ISSUE TITLE
Supports custom field acquisition and setting

### ISSUE THREAD

**Issue by laterdayi** [onepub-dev/pubspec_manager#13]
Supports custom field acquisition and setting

```
name: 'name'
description: "A new Flutter project."
publish_to: "none"
test: 'test',
test1: 'test1'

```

**Comment by bsutton** [comment]
You already do this via the Document level api, though perhaps a little crudely.

https://pub.dev/documentation/pubspec_manager/latest/pubspec_manager/Document-class.html

**Comment by laterdayi** [comment]
Can you roughly describe which API I should use? It seems a bit confusing now.

**Comment by bsutton** [comment]
```
final pubspec  = PubSpec.load();
pubspec.document.getLineForKey('test1');
```

**Comment by bsutton** [comment]
Stale
