### ISSUE TITLE
Whether name can be made optional

### ISSUE THREAD

**Issue by laterdayi** [onepub-dev/pubspec_manager#6]
Whether name can be made optional

I have a scenario where I need to get the project pubspec.yaml file, get the version value and modify the version value, how will this be done

**Comment by bsutton** [comment]
I'm not certain how this relates to the name.

There is an example of this in the readme.

```
void updateVersion() {
  final pubspec = PubSpec.load();
  pubspec.version.set('1.2.1');
  pubspec.save();
}
```
