### ISSUE TITLE
Request: version variables

### ISSUE THREAD

**Issue by Rodsevich** [onepub-dev/pubspec_manager#8]
What do you think about providing yaml variables funcitonality. Something like [isar versioning](https://pub.dev/packages/isar#1-add-to-pubspecyaml)

The code could be something like
```dart
YamlVariable('isar_version', '^4.0.0-dev.14');
```
and the usage could be sth like:
```dart
pubspec.yamlVariables.add(YamlVariable('isar_version', '^4.0.0-dev.14'));
pubspec.dependencies.add(DependencyBuilderPubHosted(name: 'isar',versionConstraint: '*isar_version'));
```

**Comment by bsutton** [comment]
First thing to know is that pubspec_manager isn't a yaml parser.

To support yaml variables would be a fair amount of work.
I've never seen  a pubspec with a yaml variables but of course that doesn't
mean they don't exist.

This isn't something I have time to do at the moment but if you want to
submit a pr I'm not opposed to the idea.

**Comment by Rodsevich** [comment]
never mind... pub is not ready yet in several of its commands to support this variables
