### ISSUE TITLE
Request: a way for extended usage

### ISSUE THREAD

**Issue by Rodsevich** [onepub-dev/pubspec_manager#9]
What do you think about providing a way of facilitating custom usage of `PubSpec` with things currently not supported?

### e.g.: 
Suppose I want to programmatically add the classic
```yaml
flutter:
  uses-material-design: true
  generate: true
```
at the end of `pubspec.yaml`
I was thinking on how to do that and I stumbled upon 2 approaches:

##### the fancy way, through
```dart
Extension('flutter', {'uses-material-design': 'true', 'generate': 'true'})
```
##### or with access to the very string of the pubspec:
```dart
pubspec.load()..source.append('''flutter:
  uses-material-design: true
  generate: true
''')..save();
```

I think both will be nice to have in this package

**Comment by bsutton** [comment]
This is already available.

Have a look at the document class.

pubspec.document.

**Comment by bsutton** [comment]
closing as stale.
